# @Project Makefile_Teamplate
# @author Enniscai
# @date 2013-11-13
# @brief Makefile example for make static library.

# You must set the PATH_ROOT_PRJ environment variable.
include $(PATH_PARSE_ROOT)/makefile.parse_root
include $(PATH_MINI_HYDRA_ROOT)/makeinclude/projects/makefile.mini_hydra

.PHONY: all clean cleanall

TARGET = libjsoncpp.a

include $(PATH_MINI_HYDRA_ROOT)/makeinclude/rule/rule_for_lib.mk
